name: Docker

on:
  workflow_dispatch:
  push:
    tags:
    - v*

jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
          echo "TAG=v1.0.0" >> $GITHUB_ENV
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build the Docker image
        if: steps.generate_tag.outputs.latest == 'false'
        run: |
          docker buildx build --push --platform linux/amd64 -t papagaye/docker-intel-gpu-tools:latest -t papagaye/docker-intel-gpu-tools:${TAG} .
